### ISSUE TITLE
mailpile.is certificate not trusted

### ISSUE THREAD

**Issue by bjmgeek** [mailpile/www.mailpile.is#22]
The certificate for mailpile.is (but not the one for www.mailpile.is) is issued by StartCom, which is no longer trusted by browsers.  Since www.mailpile.is already uses LetsEncrypt, please use LetsEncrypt for mailpile.is as well.

See https://www.ssllabs.com/ssltest/analyze.html?d=mailpile.is for example.  

More info at 
* https://blog.qualys.com/ssllabs/2017/04/05/ssl-labs-distrusts-wosign-and-startcom-certificates
* https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates
* https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html
* https://support.apple.com/en-us/HT204132

**Comment by BjarniRunar** [comment]
This is wrong.

Modern browsers are distrusting NEW certificates from those vendors. Not old certificates. This fact is right there in the URLs you've pasted, and would have been clear to you if you'd read the articles.

Visiting the URL using a modern Firefox works just fine, it redirects without an error. This is yet another case of people misunderstanding the output from SSLLabs, without understanding the bigger picture. Guess what: SSLLabs isn't perfect! It's a tool, not an oracle of truth.

Also, to be 100% clear - this is not and never has been a security issue. The action against SSLLabs and WoSign was a punitive measure to punish them for not following all the rules. Their "crime" was back-dating a few certs to help customers who were having practical difficulties caused by the forced deprecation of SHA-1 signatures. No actual security risk related to these certificates was ever demonstrated, which is why browsers still trust older (pre-punishment) certs.

We'll be switching to letsencrypt soon anyway, because the current certificate expires soon. But for now this is working fine.

**Comment by bjmgeek** [comment]
I only mentioned it because your current certificate is giving me a security error in Chrome right now.

![screenshot from 2017-07-03 09-27-55](https://user-images.githubusercontent.com/460013/27794896-066fe994-5fd2-11e7-8fc0-b69d41233a40.png)

**Comment by BjarniRunar** [comment]
That's a shame, whoever is responsible for that has overreached.

I know Debian testing is currently mistaken in this way, see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858539 - There were also bugs with the certificate store on Windows which caused issues with StartCom certificates, but that was a while back.

We'll be switching to letsencrypt soon.
