### ISSUE TITLE
add voidlinux to the distribution list

### ISSUE THREAD

**Issue by icf20** [mailpile/www.mailpile.is#23]
sudo [xbps-install](https://wiki.voidlinux.eu/XBPS#xbps-install) -S mailpile

template here https://github.com/voidlinux/void-packages/blob/master/srcpkgs/mailpile/template

**Comment by BjarniRunar** [comment]
Yeah, nope! That recipe is telling people to install an extremely out of date and insecure version. We don't want people to do that, so we won't be telling people to do that. :-)

We aren't offering packages for that version anymore, for good reasons!

**Comment by icf20** [comment]
you can always submit a pull on that template :)

**Comment by BjarniRunar** [comment]
I've never even heard of voidlinux, and sadly I know I am too busy to try it out any time soon. And since I wouldn't dream of submitting an untested pull request to someone else's hard work... no, I really can't. :-)

It's the distribution's only job to curate packages as they see fit. If they disagree with me and want to distribute that version, it is their right - it is open source after all!  I don't know if it's a mistake or they just like that version, but either way it's a bad outcome that I disagree with.

**Comment by icf20** [comment]
> I've never even heard of voidlinux

no systemd distribution and musl

> I don't know if it's a mistake or they just like that version

the rule is to pack the last stable release

**Comment by BjarniRunar** [comment]
Yep, it returns a 404 because we don't want anyone using that version. :-)  Historians can find it here in Github.

**Comment by icf20** [comment]
what's the latest stable release ?

**Comment by BjarniRunar** [comment]
There is no stable release, never has been. This confuses people. :)

Our latest release (the stablest so far) is 1.0rc1 and apparently I forgot to tag it in github.
